export const LOAD_ABOUT_SECTION_SUCCESS  = 'LOAD_ABOUT_SECTION_SUCCESS';
export const LOAD_EXPERIENCE_SUCCESS  = 'LOAD_EXPERIENCE_SUCCESS';
export const LOAD_PROJECTS_SUCCESS  = 'LOAD_PROJECTS_SUCCESS';
export const LOAD_PROJECT_PAGE_SUCCESS  = 'LOAD_PROJECT_PAGE_SUCCESS';
export const LOAD_SOCIAL_SUCCESS  = 'LOAD_SOCIAL_SUCCESS';
export const PAGE_LOADING  = 'PAGE_LOADING';
export const PAGE_LOADED  = 'PAGE_LOADED';
 